### ISSUE TITLE
[PE-D][Tester E] Help Button Links to AB3 UG instead of TP UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#121]
![image.png](https://raw.githubusercontent.com/marcuslowhuiyu/ped/main/files/4fd2d1e2-85f1-495f-b221-5b284ce9421d.png)

As mentioned in the title, the help button in the GUI now links to the AB3 User Guide instead of your TP's User Guide

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: marcuslowhuiyu/ped#1

**Comment by e1010101** [comment]
Small issue with GUI.
