### ISSUE TITLE
[PE-D][Tester E] Example Command in User Guide does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#129]
![image.png](https://raw.githubusercontent.com/marcuslowhuiyu/ped/main/files/9a6e3349-7e13-4655-a0bd-ebe56a80ebf3.png)

![image.png](https://raw.githubusercontent.com/marcuslowhuiyu/ped/main/files/dc9d0097-f9aa-407e-9c2e-5d0f6333528d.png)

The example code provided in the user guide does not work

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: marcuslowhuiyu/ped#4

**Comment by e1010101** [comment]
The command in the documentation does not include compulsory field for index number.

**Comment by xiaoying1129** [comment]
Fixed in https://github.com/AY2223S1-CS2103T-T08-1/tp/pull/191
