### ISSUE TITLE
[PE-D][Tester B] Predict does not show error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#133]
![image.png](https://raw.githubusercontent.com/GenFusion122/ped/main/files/eb08e715-31da-4e9c-8917-decdbd5ec269.png)

The command inside the screenshot was used to test the feature
I suspect this is because the student does not have a grade, however I am unable to add a grade, see issue 2.
Either way, I suggest implementing an error message for this, something like: "student hasn't been graded yet"

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: GenFusion122/ped#3

**Comment by e1010101** [comment]
See #183.
