### ISSUE TITLE
[PE-D][Tester E] Sort not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#138]
![image.png](https://raw.githubusercontent.com/marcuslowhuiyu/ped/main/files/28769021-1018-4444-99b4-0bc7ee16995c.png)

Tested both sort asc and sort desc. Does not seem to do anything currently.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: marcuslowhuiyu/ped#6

**Comment by e1010101** [comment]
See #180.
