### ISSUE TITLE
[PE-D][Tester E] Grade Allowing Inputs above Total Score

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#145]
I was unable to screenshot this issue due to another bug as mentioned later.

For example, if I input 100 as the maximum score, I am able to key in 101 as the value even though that is above the maximum score without the app notifying me of invalid input.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: marcuslowhuiyu/ped#8

**Comment by e1010101** [comment]
See #179.
