### ISSUE TITLE
[PE-D][Tester A] Inaccuracy in find command documentation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#146]
All parameters are listed as optional, but it is not explicitly stated that at least one of the parameters should be present. This seems to suggest that `find` by itself is a valid input. Additionally, it does not follow the square brackets for optional as mentioned at the start of the features portion.

![image.png](https://raw.githubusercontent.com/ConradLew/ped/main/files/4d647173-2540-43f8-85a0-809c2855f8a0.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ConradLew/ped#7

**Comment by e1010101** [comment]
Documentation issue.

**Comment by xiaoying1129** [comment]
Fixed in https://github.com/AY2223S1-CS2103T-T08-1/tp/pull/191
