### ISSUE TITLE
[PE-D][Tester B] Sort feature does show any error messages

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#147]
![image.png](https://raw.githubusercontent.com/GenFusion122/ped/main/files/39481354-db0e-4925-8c4b-f0d0024f3b6d.png)

It is likely because the grade command doesn't work and so I am unable to test the Sort command
However, if no students have any grades, should the sort command list out any error messages?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: GenFusion122/ped#6

**Comment by e1010101** [comment]
See #180.
