### ISSUE TITLE
[PE-D][Tester D] Not giving a clear way about adding subject to a student

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#148]
Noticed you mention about subject in grading and finding. However somehow I just cannot find how to add subject to a student. I tried add ........s/math edit 1 s/math but failed.

Expected : clearly state about subject adding ways. 

![image.png](https://raw.githubusercontent.com/bokun2/ped/main/files/7b2d830b-e8c8-4807-a4e0-6a4f86b4a188.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: bokun2/ped#5

**Comment by e1010101** [comment]
We currently don't support editing of subjects, only adding. KIV.

**Comment by Hoodineee** [comment]
Due to feature freeze and us not supporting the editing of subjects, the only way to work around it if the subject is typed wrongly is to delete the person and re-add them after.

**Comment by e1010101** [comment]
Won't add. Subjects are to be hardcoded in the json file at the moment.
