### ISSUE TITLE
[PE-D][Tester E] Suggestion: Change how Grade Parameters are Inputted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#151]
![image.png](https://raw.githubusercontent.com/marcuslowhuiyu/ped/main/files/1dd6aaa9-a29e-4da7-9f6e-ec801f911100.png)

Currently the parameters for the grade feature is not only difficult to read, it is also not consistent with the other features present in the app which uses `c\` for example.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: marcuslowhuiyu/ped#10

**Comment by e1010101** [comment]
Replace the underscore system with a prefix system of sorts. The relevant information in the UG/DG should also be updated.

**Comment by Hoodineee** [comment]
Due to feature freeze, we are unable to change the formatting of the grade command.
