### ISSUE TITLE
[PE-D][Tester B] Remark feature is not used anywhere?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#156]
![image.png](https://raw.githubusercontent.com/GenFusion122/ped/main/files/b6dff375-313f-416c-8b1b-c86330c319de.png)

Remarks seem to have no use since there's no feature to search by remarks nor is there any UI changes to the Student's card. The only existence of remark I can see is in that success message in the screenshot above. Furthermore, remarks seem to play a similar role to Tags? 

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: GenFusion122/ped#7

**Comment by e1010101** [comment]
See #163.
