### ISSUE TITLE
[PE-D][Tester D] The remark does not show after remark command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#163]
After "remark 1 I love ice!!!!" The remark content just does not show in the ui. And the UG does not provide a way for user to check the remark. I notice in UG the example ui under remark did not show remark content after adding. If the app should work like this, then I think it is better clearly state some command in UG that allow user to check remark content with the remark command.

![image.png](https://raw.githubusercontent.com/bokun2/ped/main/files/5a4e29f6-7175-4118-beba-9028cb8c0bb9.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: bokun2/ped#7

**Comment by e1010101** [comment]
UI improvement that will be largely beneficial to Quality-Of-Life. As we cannot implement this feature, we should remove the remark system completely.
