### ISSUE TITLE
[PE-D][Tester A] Additional spacing in UI where parameters are missing

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#168]
![image.png](https://raw.githubusercontent.com/ConradLew/ped/main/files/ef53b2ae-9dfe-43fb-9773-cd3d4c8dfbaf.png)

For cards where some parameters are missing, such as SUBJECT: Grade, there is an additional spacing where the parameter is supposed to be which makes the card seem poorly designed.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ConradLew/ped#13

**Comment by e1010101** [comment]
Notable issue that should be fixed when subject fields are made compulsory.
