### ISSUE TITLE
[PE-D][Tester C] Relevance of `STUDENT_CLASS` in the add command not known

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#169]
In the add command the prefix to enter the 'STUDENT_CLASS' of a person accepts any string input and the sample data displays a decimal number for 'Class' attributes of all students (assuming class or standard is never ideally a decimal number) thus, the relevance or expected input value for Class is not known. Perhaps you can consider mentioning the meaning of Student Class in the user guide for the user to enter appropriate input.

Example of format in which the user can give input for Class and example of value being displayed for Class attribute in the sample data
![image.png](https://raw.githubusercontent.com/agarwal-anjali/ped/main/files/33934b80-54d9-4d78-b957-0428521d5e0e.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: agarwal-anjali/ped#5

**Comment by e1010101** [comment]
Tested with the following command:
`add n/test ind/10 p/1111 a/test street class/      abc e/test@gmail.com`

Proposed solution: Ensure that studentClass should not start with blank spaces, and also update documentation to provide example inputs.

**Comment by e1010101** [comment]
Documentation issue. The command in the command above was in the wrong format ("class/" instead of "c/"). Handing over to @xiaoying1129.

**Comment by xiaoying1129** [comment]
Fixed in https://github.com/AY2223S1-CS2103T-T08-1/tp/pull/191
