### ISSUE TITLE
[PE-D][Tester E] Irrelevant Tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#175]
Just a minor gripe, but considering this app is meant for teachers to manage students, why is there a need to tag some of the students with `friends`, `family`, or `colleagues` tags? 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: marcuslowhuiyu/ped#17

**Comment by e1010101** [comment]
Starting data is outdated. This needs to be fixed so that fallback measures referenced in #176 give relevant starting data.

**Comment by e1010101** [comment]
Fixed by #186.
