### ISSUE TITLE
[PE-D][Tester A] Inaccuracy in remark documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#178]
![image.png](https://raw.githubusercontent.com/ConradLew/ped/main/files/643834c5-c72d-45ff-942e-7c8f60fb329b.png)

Remark is not meant to be an optional parameter here but uses square brackets.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ConradLew/ped#15

**Comment by e1010101** [comment]
Documentation inaccuracy.

**Comment by xiaoying1129** [comment]
Fixed in https://github.com/AY2223S1-CS2103T-T08-1/tp/pull/191
