### ISSUE TITLE
[PE-D][Tester A] Entries beyond the maximum mark in grade

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#179]
It is possible to give marks beyond the maximum mark for the grade command i.e. grade MATH_CA1_100_0.5_1.0, but give grades beyond 100 without any warning or error message displayed. Negative values are allowed to. Low severity as most people would enter marks from a spreadsheet which should contain valid values, but can cause inconvenience if the data itself is inaccurate.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ConradLew/ped#16

**Comment by e1010101** [comment]
Check needs to be applied in the parsing process.

**Comment by Hoodineee** [comment]
Constraints for maximum mark have been added. Left with an error message for when score exceeds total score.
