### ISSUE TITLE
[PE-D][Tester C] Remarks for a student is not being displayed in the GUI

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#182]
Perhaps you can consider displaying the remarks for a person, as although on adding/editing a remark using the 'remark'/'edit' commands a message is being displayed that the remark got added/edited, adding/editing remarks become a redundant feature if user cannot view the remarks after adding or editing it for a person!
![image.png](https://raw.githubusercontent.com/agarwal-anjali/ped/main/files/2e55c62f-975c-4530-bbae-ed314e951d40.png)

![image.png](https://raw.githubusercontent.com/agarwal-anjali/ped/main/files/a7dd676b-8a88-4f27-9bda-f369d0326391.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: agarwal-anjali/ped#8

**Comment by e1010101** [comment]
This is a good point! We will look into further GUI improvements for v1.4.

**Comment by e1010101** [comment]
See #163.
