### ISSUE TITLE
[PE-D][Tester C] Predict command throws unhandled exceptions and does not display any error message on the GUI for the same

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#183]
On entering the following command:

![image.png](https://raw.githubusercontent.com/agarwal-anjali/ped/main/files/f75a1dc1-2947-4c36-938e-32a7cbe04ab9.png)

![image.png](https://raw.githubusercontent.com/agarwal-anjali/ped/main/files/34f94a8c-197b-43f1-a2c7-f5c1bc6c0ba3.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: agarwal-anjali/ped#9

**Comment by e1010101** [comment]
Update the parsing process to "find" names that match partial input. This should also be case-insensitive.
